name: Convert Readme
on: 'push'
jobs:
  tag:
    name: Convert Readme1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Convert Readme
        uses: evrpress/wp2md@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: false
